version: '3'
services:
  app:
    platform: linux/amd64
    build: .
    image: maayanlab/generanger:0.3.16
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL='postgres://postgres:${POSTGRES_PASSWORD}@127.0.0.1:5432/postgres?sslmode=disable'
      - NEXT_PUBLIC_DOWNLOADS=https://minio.dev.maayanlab.cloud/generanger/
      - NEXT_PUBLIC_TARGETRANGERURL=https://targetranger.dev.maayanlab.cloud/targetscreener
      - NEXT_PUBLIC_ENTRYPOINT=
    ports:
      - 3000:80