version: '3'
services:
  db:
    platform: linux/x86_64
    build: .
    image: maayanlab/postgres-py
    environment:
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
